import { Badge } from '@/components/ui/badge'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { getOverviewData } from '@/lib/dashboard/getOverviewData'
import { getCostOverview } from '@/lib/dashboard/getCostOverview'
import { getGoogleStatus } from '@/lib/dashboard/getGoogleStatus'
import { getTodos } from '@/lib/dashboard/getTodos'
import { getPerformanceInsights } from '@/lib/dashboard/getPerformanceInsights'
import { TodoListCard } from '@/components/dashboard/TodoListCard'
import { GoogleSyncCard } from '@/components/dashboard/GoogleSyncCard'
import Link from 'next/link'
import { Sparkles, TrendingUp, AlertCircle, FileText, CheckCircle2, ArrowRight, Activity, Search, Bot, Zap } from 'lucide-react'

export default async function DashboardPage() {
  const [overview, cost, google, todos, perf] = await Promise.all([
    getOverviewData(), 
    getCostOverview(), 
    getGoogleStatus(), 
    getTodos(8), 
    getPerformanceInsights()
  ])

  // Compute tasks based on data
  const hasPendingItems = overview.pendingNieuws > 0
  const hasSchemaIssues = overview.workspaceStats.some(w => (w.pages - w.pagesWithSchema) > 0)
  const isBudgetAlert = (cost?.overBudgetAgents ?? 0) > 0

  return (
    <section className="mx-auto max-w-7xl space-y-8 pb-12">
      {/* HERO HEADER */}
      <header className="relative overflow-hidden rounded-3xl border border-gray-200/50 bg-white/60 p-8 shadow-xl backdrop-blur-xl dark:border-gray-800/50 dark:bg-gray-950/40">
        <div className="absolute top-0 -left-20 h-64 w-64 rounded-full bg-orange-500/20 blur-[100px]" />
        <div className="absolute -right-20 -bottom-20 h-64 w-64 rounded-full bg-indigo-500/20 blur-[100px]" />
        
        <div className="relative z-10 flex flex-col md:flex-row md:items-end justify-between gap-6">
          <div className="space-y-3">
            <div className="inline-flex items-center gap-2 rounded-full border border-orange-200 bg-orange-50 px-3 py-1 text-xs font-semibold text-orange-700 dark:border-orange-500/30 dark:bg-orange-500/10 dark:text-orange-400">
              <Sparkles className="h-3.5 w-3.5" />
              <span>AI SEO Engine Active</span>
            </div>
            <h1 className="text-3xl font-bold tracking-tight text-gray-900 dark:text-white sm:text-4xl">
              Content & SEO Command Center
            </h1>
            <p className="max-w-2xl text-base text-gray-500 dark:text-gray-400 leading-relaxed">
              Your intelligent companion for organic growth. We monitor your search performance, analyze LLM visibility, and actively generate high-converting content.
            </p>
          </div>
          
          <div className="flex shrink-0 items-center gap-3">
            <Link href="/dashboard/nieuws" className="group flex items-center gap-2 rounded-xl bg-gradient-to-r from-orange-500 to-indigo-500 px-5 py-2.5 text-sm font-medium text-white shadow-md transition-all hover:scale-[1.02] hover:shadow-lg dark:hover:shadow-orange-500/20">
              <Bot className="h-4 w-4" />
              <span>Generate Article</span>
            </Link>
          </div>
        </div>
      </header>

      {/* ACTION CENTER - WHAT TO DO TODAY */}
      <div className="space-y-4">
        <div className="flex items-center gap-2">
          <Zap className="h-5 w-5 text-orange-500" />
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white">Action Center</h2>
        </div>
        
        <div className="grid gap-4 md:grid-cols-3">
          {/* Action 1: Pending Reviews */}
          <div className="group relative flex cursor-pointer flex-col justify-between overflow-hidden rounded-2xl border border-gray-200/60 bg-white p-5 shadow-sm transition-all hover:border-orange-500/30 hover:shadow-md dark:border-gray-800/60 dark:bg-gray-900/50">
            <div className="absolute right-0 top-0 h-32 w-32 -translate-y-8 translate-x-8 rounded-full bg-blue-500/10 blur-[40px] transition-all group-hover:bg-blue-500/20" />
            <div className="space-y-4 z-10">
              <div className={`inline-flex rounded-lg p-2 ${hasPendingItems ? 'bg-orange-100 text-orange-600 dark:bg-orange-500/20 dark:text-orange-400' : 'bg-green-100 text-green-600 dark:bg-green-500/20 dark:text-green-400'}`}>
                {hasPendingItems ? <AlertCircle className="h-5 w-5" /> : <CheckCircle2 className="h-5 w-5" />}
              </div>
              <div>
                <h3 className="text-base font-semibold text-gray-900 dark:text-white">Review Pending Content</h3>
                <p className="mt-1 text-sm text-gray-500 dark:text-gray-400">
                  {hasPendingItems ? `You have ${overview.pendingNieuws} articles generated by the LLM waiting for review before publishing.` : 'All generated content has been published automatically.'}
                </p>
              </div>
            </div>
            <div className="mt-5 z-10">
              <Link href="/dashboard/nieuws" className="inline-flex items-center gap-2 text-sm font-medium text-blue-600 hover:text-blue-700 dark:text-blue-400 dark:hover:text-blue-300">
                {hasPendingItems ? 'Review articles' : 'Generate new articles'} <ArrowRight className="h-4 w-4" />
              </Link>
            </div>
          </div>

          {/* Action 2: Schema Health */}
          <div className="group relative flex cursor-pointer flex-col justify-between overflow-hidden rounded-2xl border border-gray-200/60 bg-white p-5 shadow-sm transition-all hover:border-emerald-500/30 hover:shadow-md dark:border-gray-800/60 dark:bg-gray-900/50">
            <div className="absolute right-0 top-0 h-32 w-32 -translate-y-8 translate-x-8 rounded-full bg-emerald-500/10 blur-[40px] transition-all group-hover:bg-emerald-500/20" />
            <div className="space-y-4 z-10">
              <div className={`inline-flex rounded-lg p-2 ${hasSchemaIssues ? 'bg-amber-100 text-amber-600 dark:bg-amber-500/20 dark:text-amber-400' : 'bg-emerald-100 text-emerald-600 dark:bg-emerald-500/20 dark:text-emerald-400'}`}>
                <FileText className="h-5 w-5" />
              </div>
              <div>
                <h3 className="text-base font-semibold text-gray-900 dark:text-white">Optimize Content Structure</h3>
                <p className="mt-1 text-sm text-gray-500 dark:text-gray-400">
                  {overview.structuredCoverage}% schema coverage. {hasSchemaIssues ? 'Missing structured data can reduce search visibility and LLM citations.' : 'Your content is optimally structured for search engines.'}
                </p>
              </div>
            </div>
            <div className="mt-5 z-10">
              <Link href="/dashboard/status" className="inline-flex items-center gap-2 text-sm font-medium text-emerald-600 hover:text-emerald-700 dark:text-emerald-400 dark:hover:text-emerald-300">
                Fix SEO issues <ArrowRight className="h-4 w-4" />
              </Link>
            </div>
          </div>

          {/* Action 3: Automation Status */}
          <div className="group relative flex cursor-pointer flex-col justify-between overflow-hidden rounded-2xl border border-gray-200/60 bg-white p-5 shadow-sm transition-all hover:border-indigo-500/30 hover:shadow-md dark:border-gray-800/60 dark:bg-gray-900/50">
            <div className="absolute right-0 top-0 h-32 w-32 -translate-y-8 translate-x-8 rounded-full bg-indigo-500/10 blur-[40px] transition-all group-hover:bg-indigo-500/20" />
            <div className="space-y-4 z-10">
              <div className={`inline-flex rounded-lg p-2 ${!google?.ga4Ready ? 'bg-rose-100 text-rose-600 dark:bg-rose-500/20 dark:text-rose-400' : 'bg-indigo-100 text-indigo-600 dark:bg-indigo-500/20 dark:text-indigo-400'}`}>
                <Activity className="h-5 w-5" />
              </div>
              <div>
                <h3 className="text-base font-semibold text-gray-900 dark:text-white">Workspace Health & Connections</h3>
                <p className="mt-1 text-sm text-gray-500 dark:text-gray-400">
                  {!google?.ga4Ready ? 'Google Search Console / GA4 integration is incomplete. Sync required.' : `${google?.gscConnected} workspaces fully integrated with Analytics & Search Console.`}
                </p>
              </div>
            </div>
            <div className="mt-5 z-10">
              <Link href="/dashboard/google" className="inline-flex items-center gap-2 text-sm font-medium text-indigo-600 hover:text-indigo-700 dark:text-indigo-400 dark:hover:text-indigo-300">
                Manage connections <ArrowRight className="h-4 w-4" />
              </Link>
            </div>
          </div>
        </div>
      </div>

      {/* KPI STRIP - REDESIGNED */}
      <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-5 gap-3">
        <KpiCard title="Organic Clicks" value={overview.totalClicks30d.toLocaleString('nl-NL')} trend="+12%" icon={<Search className="h-4 w-4" />} />
        <KpiCard title="LLM Mentions" value={overview.totalMentions30d.toLocaleString('nl-NL')} trend="+24%" icon={<Bot className="h-4 w-4" />} color="emerald" />
        <KpiCard title="Schema Health" value={`${overview.structuredCoverage}%`} trend="Stable" icon={<FileText className="h-4 w-4" />} />
        <KpiCard title="Pending Review" value={overview.pendingNieuws.toString()} isAlert={overview.pendingNieuws > 0} icon={<FileText className="h-4 w-4" />} />
        <KpiCard title="AI Agent Spend" value={cost ? `$${cost.monthUsd.toFixed(2)}` : 'n/a'} isAlert={isBudgetAlert} icon={<Activity className="h-4 w-4" />} />
      </div>

      <div className="grid gap-6 md:grid-cols-3">
        {perf.byDomain.slice(0, 3).map((d) => (
          <div key={d.domain} className="group relative overflow-hidden rounded-xl border border-gray-200/50 bg-white p-5 shadow-sm dark:border-gray-800/50 dark:bg-gray-900">
            <div className="mb-4 flex items-center justify-between">
              <p className="text-sm font-semibold text-gray-900 dark:text-gray-100">{d.domain}</p>
              <TrendingUp className="h-4 w-4 text-emerald-500" />
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <p className="text-xs text-gray-500">Clicks</p>
                <p className="font-medium text-gray-900 dark:text-white">{d.clicks.toLocaleString()}</p>
                <p className={`text-[10px] ${d.deltaClicksPct >= 0 ? 'text-emerald-500' : 'text-rose-500'}`}>
                  {d.deltaClicksPct >= 0 ? '+' : ''}{d.deltaClicksPct.toFixed(1)}%
                </p>
              </div>
              <div>
                <p className="text-xs text-gray-500">Sessions</p>
                <p className="font-medium text-gray-900 dark:text-white">{d.sessions.toLocaleString()}</p>
                <p className={`text-[10px] ${d.deltaSessionsPct >= 0 ? 'text-emerald-500' : 'text-rose-500'}`}>
                  {d.deltaSessionsPct >= 0 ? '+' : ''}{d.deltaSessionsPct.toFixed(1)}%
                </p>
              </div>
            </div>
          </div>
        ))}
      </div>

      <div className="grid gap-6 lg:grid-cols-2">
        <TodoListCard items={todos} />
        <GoogleSyncCard />
      </div>

      {/* WORKSPACE OVERVIEWS */}
      <div className="space-y-4">
        <div className="flex items-center gap-2">
          <Activity className="h-5 w-5 text-indigo-500" />
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white">Workspace Analytics Engine</h2>
        </div>
        
        <div className="grid gap-4 xl:grid-cols-3">
          {overview.workspaceStats.map((workspace) => {
            const schemaCoverage = workspace.pages === 0 ? 0 : Math.round((workspace.pagesWithSchema / workspace.pages) * 100)
            return (
              <Card key={workspace.id} className="overflow-hidden border-gray-200/50 shadow-sm transition-all hover:-translate-y-1 hover:shadow-md dark:border-gray-800/50 dark:bg-gray-950/40">
                <CardHeader className="space-y-1 bg-gradient-to-r from-gray-50 to-white dark:from-gray-900/50 dark:to-gray-900">
                  <CardTitle className="text-base flex justify-between items-center">
                    {workspace.domain}
                    <Badge variant="outline" className="border-indigo-200 text-indigo-700 bg-indigo-50 dark:border-indigo-900 dark:text-indigo-400 dark:bg-indigo-950">Active</Badge>
                  </CardTitle>
                  <CardDescription>{workspace.displayName}</CardDescription>
                </CardHeader>
                <CardContent className="space-y-4 pt-4">
                  <div className="grid grid-cols-2 gap-3 text-sm">
                    <StatItem label="Indexed Pages" value={workspace.pages} />
                    <StatItem label="Schema Health" value={`${schemaCoverage}%`} />
                    <StatItem label="Organic Clicks" value={workspace.clicks30d} />
                    <StatItem label="LLM Mentions" value={workspace.mentions30d} />
                  </div>
                  <div className="mt-4 pt-4 border-t border-gray-100 dark:border-gray-800 flex items-center justify-between">
                    <div className="flex gap-2">
                       {workspace.pendingNieuws > 0 && (
                          <span className="flex items-center gap-1 text-xs font-medium text-orange-600 dark:text-orange-400">
                            <span className="relative flex h-2 w-2">
                              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-orange-400 opacity-75"></span>
                              <span className="relative inline-flex rounded-full h-2 w-2 bg-orange-500"></span>
                            </span>
                            {workspace.pendingNieuws} requires review
                          </span>
                       )}
                    </div>
                    <Link href={`/dashboard/${workspace.id}`} className="text-sm font-medium text-indigo-600 hover:text-indigo-700 dark:text-indigo-400 dark:hover:text-indigo-300 flex items-center gap-1 group">
                      Deep Dive <ArrowRight className="h-3 w-3 transition-transform group-hover:translate-x-1" />
                    </Link>
                  </div>
                </CardContent>
              </Card>
            )
          })}
        </div>
      </div>
    </section>
  )
}

function KpiCard({ title, value, trend, isAlert, icon, color = 'indigo' }: { title: string; value: string; trend?: string; isAlert?: boolean; icon: React.ReactNode; color?: 'indigo' | 'emerald' | 'orange' }) {
  return (
    <div className={`relative overflow-hidden rounded-xl border ${isAlert ? 'border-amber-200 bg-amber-50 dark:border-amber-900/50 dark:bg-amber-900/20' : 'border-gray-200/60 bg-white dark:border-gray-800/50 dark:bg-gray-900/40'} p-4 shadow-sm`}>
      <div className="flex text-gray-500 dark:text-gray-400 mb-2 gap-2 justify-between items-center">
        <span className="text-xs font-semibold uppercase tracking-wider">{title}</span>
        {icon}
      </div>
      <div className="flex items-baseline gap-2">
        <span className={`text-2xl font-bold ${isAlert ? 'text-amber-700 dark:text-amber-500' : 'text-gray-900 dark:text-white'}`}>{value}</span>
      </div>
      {trend && (
        <p className="mt-1 text-[11px] font-medium text-emerald-600 dark:text-emerald-400">
           {trend} last 30d
        </p>
      )}
    </div>
  )
}

function StatItem({ label, value }: { label: string; value: number | string }) {
  return (
    <div>
      <p className="text-[10px] uppercase tracking-wider text-gray-500 dark:text-gray-400 mb-1">{label}</p>
      <p className="text-sm font-semibold text-gray-900 dark:text-gray-100">{value}</p>
    </div>
  )
}
